server:
  port: 5050

logging:
  level:
    org:
      apache:
        kafka: warn
    io:
      github:
        alikelleci:
          eventify: debug

spring:
  application:
    name: "example-app"
  kafka:
    bootstrap-servers: "localhost:9092"
